# Generated by Django 5.2 on 2025-05-03 10:57

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Введите наименование продукта",
                        max_length=250,
                        verbose_name="Наименование",
                    ),
                ),
                (
                    "model",
                    models.CharField(
                        help_text="Введите модель продукта",
                        max_length=250,
                        verbose_name="Модель",
                    ),
                ),
                (
                    "release_date",
                    models.DateField(
                        help_text="Введите дату выхода продукта на рынок",
                        verbose_name="Дата выхода продукта на рынок",
                    ),
                ),
            ],
            options={
                "verbose_name": "продукт",
                "verbose_name_plural": "продукты",
                "ordering": ["name", "release_date"],
            },
        ),
        migrations.CreateModel(
            name="Link",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Введите наименование звена",
                        max_length=250,
                        verbose_name="Наименование",
                    ),
                ),
                (
                    "debt",
                    models.FloatField(
                        default=0.0,
                        help_text="Укажите величину задолженности",
                        validators=[django.core.validators.MinValueValidator(0.0)],
                        verbose_name="задолженность перед поставщиком",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "provider",
                    models.ForeignKey(
                        blank=True,
                        help_text="Укажите поставщика",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="retail_network.link",
                        verbose_name="поставщик",
                    ),
                ),
                (
                    "products",
                    models.ManyToManyField(
                        related_name="products",
                        to="retail_network.product",
                        verbose_name="продукты",
                    ),
                ),
            ],
            options={
                "verbose_name": "звено",
                "verbose_name_plural": "звенья",
                "ordering": ["name", "debt"],
            },
        ),
        migrations.CreateModel(
            name="Contacts",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        help_text="Введите Email",
                        max_length=254,
                        null=True,
                        verbose_name="Email",
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        blank=True,
                        help_text="Введите страну",
                        max_length=150,
                        null=True,
                        verbose_name="Страна",
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        blank=True,
                        help_text="Введите город",
                        max_length=150,
                        null=True,
                        verbose_name="Город",
                    ),
                ),
                (
                    "street",
                    models.CharField(
                        blank=True,
                        help_text="Введите улицу",
                        max_length=150,
                        null=True,
                        verbose_name="Улица",
                    ),
                ),
                (
                    "house_number",
                    models.CharField(
                        blank=True,
                        help_text="Введите номер дома",
                        max_length=150,
                        null=True,
                        verbose_name="Номер дома",
                    ),
                ),
                (
                    "link",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contacts",
                        to="retail_network.link",
                        verbose_name="Звено",
                    ),
                ),
            ],
            options={
                "verbose_name": "контакты",
                "verbose_name_plural": "контактов",
            },
        ),
    ]
